export let state = [
  "Maharashtra",
  "Delhi",
  "Karnataka",
  "Andhra Pradesh",
  "Gujarat",
  "Tamil Nadu",
  "West Bengal",
  "Maharashtra",
  "Rajasthan",
  "Gujarat",
  "Utter Pradesh",
  "Utter Pradesh",
  "Maharashtra",
  "Bihar",
  "Madhya Pradesh",
  "Maharashtra",
  "BMadhya Pradesh",
  "Andhra Pradesh",
  "Gujarat",
  "Uttar Pradesh",
  "Punjab",
  "Gujarat",
  "Uttar Pradesh",
  "West Bengal",
  "Maharashtra",
  "Haryana",
  "Punjab",
  "Utter Pradesh",
  "Maharashtra",
  "Utter Pradesh",
];
